{% set name = "libpcap" %}
{% set version = "1.10.4" %}
{% set sha256 = "ed19a0383fad72e3ad435fd239d7cd80d64916b87269550159d20e47160ebe5f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.tcpdump.org/release/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix-install.patch  # [win]

build:
  number: 1
  run_exports:
    # Symbols were last removed on update from 1.7 to 1.8
    # https://abi-laboratory.pro/index.php?view=timeline&l=libpcap
    - {{ pin_subpackage(name, max_pin='x.x') }}
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf              # [not win]
    - flex                  # [not win]
    - bison                 # [not win]
    - m4                    # [not win]
    - make                  # [not win]
    - cmake                 # [win]
    - ninja                 # [win]
    - winflexbison          # [win]
    - pkg-config            # [not win]
  host:
    # For remote capture support
    - openssl               # [win]


test:
  commands:
    - test -f $PREFIX/lib/libpcap${SHLIB_EXT}   # [not win]
    - test -f $PREFIX/include/pcap.h            # [not win]
    - if not exist "%LIBRARY_LIB%\\pcap.lib" exit 1   # [win]
    - if not exist "%LIBRARY_BIN%\\pcap.dll" exit 1   # [win]
    - if not exist "%LIBRARY_INC%\\pcap.h" exit 1     # [win]

about:
  home: www.tcpdump.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: the LIBpcap interface to various kernel packet capture mechanism
  doc_url: http://www.tcpdump.org/#documentation
  dev_url: https://github.com/the-tcpdump-group/libpcap

extra:
  recipe-maintainers:
    - nehaljwani
    - seanyen
