appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: a6nvwTiGT7LiQ//Jc0UsmO+8GS2S5PaoMHSpMKVF53e9eqZeBOTi2MFbpDAeYDAJudjQKgDWgDndnongWz++EOoov2G9toTFafZ5/8B24tqiWHdtl3sNRdo0KJ8T5WEkznKWsr68m214L4i4y2mmn2jUQWxR1lP+eMUu8bwkmWAsa6oNN3od01qRy5SDGnsewXyGGw2umi1MB6BnZjG/gMi/cm3iYvr8wb1miGNAn1hkwz/sUustQA98OE9GoG/W8bm9nlatRmdnE2OyT+zvg5Vb47n9TU+4qBvjkaXlViTj3t09LC15PCM+ZM3S91Jbdm5A7+NX/dDbnfPPw4+Wrb7lOI7HzXDys0NjibTWe31wGOyx8sDEkVcxF7oAz6rt7Z6wHEbACSnndC4gzNUV2wN4PA/C40qUUFQ9uVwE9Q8tZOfKSxMxAipbLl2aJPzFSQ9ApGwv6M1sMsfBwUT/FFQ3fXK0C8yWU2AvVYQqcsdk676z94Swrr3gxilnLC8YQkNrHV4sa83j5uYbjX5a6F7ap1J62bgGwwyFNzIc6BnQ1TyUYgLYsVtpU3v3k3/q+pccLjmdqw/gpRvecCf10Cj3hGMPNDbkM1yemNSIl5muEhWjI3OvD6MftW9NgWHzT4jCV0e3X073gjkW1VoBLD19wOCrGkdO6y1ctNwg9l8=}
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
conda_forge_output_validation: true
